name: Bump Homebrew Formula
on:
  release:
    types: [published]

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Upsert formula
        uses: pmunin/homebrew-actions/upsert-formula@main
        with:
          formula-name: gtasks
          formula-template-path: homebrew-formula.rb
          extra-envs: |
            TAG=${{ github.event.release.tag_name }}
